import {
  beforeAll,
  describe,
  expect,
  it,
} from "vitest";

import {
  existsSync,
  readFileSync,
} from "node:fs";

import {
  fileURLToPath,
} from "node:url";

import {
  resolveDefaultValue,
} from "./resolve-default-value";

import type {
  RegulatoryRecord,
} from "./types";

// Anchored to this file's location (not process.cwd()) so the test works
// regardless of which directory vitest is invoked from.
const DATASET_PATH =
  fileURLToPath(
    new URL(
      "../../../data/processed/default-emission-values-definitive.json",
      import.meta.url,
    ),
  );

// This canonical dataset is gitignored (it is generated by the Python
// pipeline from the source workbook — see scripts/regulatory/) and is not
// present on a fresh clone. Skip rather than fail collection when it is
// absent, matching the skip semantics of the Supabase integration suites.
const datasetAvailable =
  existsSync(
    DATASET_PATH,
  );

function loadDataset(): RegulatoryRecord[] {
  const raw = readFileSync(
    DATASET_PATH,
    "utf-8",
  );

  // The canonical JSON predates the dataset_version field added to
  // RegulatoryRecord (see docs/adr/ADR-0010-...); this cast tolerates
  // its absence here because no test in this file asserts on it. The
  // canonical JSON itself is not regenerated for this — it is the
  // parser's/pipeline's output, not something this test suite owns.
  return JSON.parse(
    raw,
  ) as RegulatoryRecord[];
}

describe.skipIf(!datasetAvailable)(
  "resolveDefaultValue against definitive dataset",
  () => {
    let records: RegulatoryRecord[];

    beforeAll(() => {
      records =
        loadDataset();
    });

    it(
      "contains the expected India CN8 record",
      () => {
        const matches =
          records.filter(
            (record) =>
              record.origin_country_name ===
                "India"
              && record.normalized_trade_code ===
                "72061000",
          );

        expect(
          matches.length,
        ).toBeGreaterThan(0);

        expect(
          matches.some(
            (record) =>
              record.code_level ===
              "CN8",
          ),
        ).toBe(true);
      },
    );

    it(
      "resolves India 72061000",
      () => {
        const result =
          resolveDefaultValue(
            records,
            {
              origin_country_name:
                "India",

              trade_code:
                "72061000",

              production_route:
                "(C)",
            },
          );

        expect(
          result.status,
        ).toBe("RESOLVED");

        expect(
          result.reason,
        ).toBe(
          "EXACT_CN8_MATCH",
        );

        expect(
          result.record
            ?.normalized_trade_code,
        ).toBe(
          "72061000",
        );

        expect(
          result.record
            ?.total_emissions.status,
        ).toBe(
          "AVAILABLE",
        );
      },
    );

    it(
      "resolves India 31021012",
      () => {
        const result =
          resolveDefaultValue(
            records,
            {
              origin_country_name:
                "India",

              trade_code:
                "31021012",
            },
          );

        expect(
          result.status,
        ).toBe("RESOLVED");

        expect(
          result.record
            ?.normalized_trade_code,
        ).toBe(
          "31021012",
        );

        expect(
          result.record
            ?.total_emissions.value,
        ).toBe(
          "0.740",
        );
      },
    );

    it(
      "finds the India TARIC record",
      () => {
        const matches =
          records.filter(
            (record) =>
              record.origin_country_name ===
                "India"
              && record.normalized_trade_code ===
                "2507008080",
          );

        expect(
          matches.length,
        ).toBe(1);

        expect(
          matches[0]
            ?.code_level,
        ).toBe(
          "TARIC10",
        );
      },
    );

    it(
      "does not convert unavailable TARIC to zero",
      () => {
        const matches =
          records.filter(
            (record) =>
              record.origin_country_name ===
                "India"
              && record.normalized_trade_code ===
                "2507008080",
          );

        expect(
          matches.length,
        ).toBe(1);

        const sourceRecord =
          matches[0];

        if (!sourceRecord) {
          throw new Error(
            "Expected India 2507008080 record",
          );
        }

        const result =
          resolveDefaultValue(
            records,
            {
              origin_country_name:
                "India",

              trade_code:
                "2507008080",
            },
          );

        if (
          sourceRecord
            .total_emissions
            .status ===
          "UNAVAILABLE"
        ) {
          // 2026-08-30 (R7 clause 2 / R9 fix, primary-source-confirmed --
          // see docs/regulatory/R7_R9_COUNTRY_FALLBACK_DECISION_MEMO.md):
          // this test previously asserted UNRESOLVED/UNAVAILABLE here.
          // India's real "2507008080" row is exactly the R7-clause-2
          // case -- explicitly listed, but its own value is unavailable
          // -- and the resolver now attempts the Other Countries and
          // Territories fallback for this code before giving up, per
          // Commission Implementing Regulation (EU) 2025/2621, Annex I
          // (read directly, confirmed unchanged by its correction (EU)
          // 2026/1740). In the real ACTIVE dataset that fallback IS
          // available, so this specific real row now resolves via
          // OTHER_COUNTRIES_FALLBACK instead of staying unresolved --
          // this is the fix working correctly against real production
          // data, not a regression. The invariant this test exists to
          // prove -- never a fabricated zero -- is asserted directly
          // below rather than assumed from the status change alone.
          expect(
            result.status,
          ).toBe(
            "RESOLVED",
          );

          expect(
            result.reason,
          ).toBe(
            "OTHER_COUNTRIES_FALLBACK",
          );

          expect(
            result.record
              ?.total_emissions.status,
          ).toBe(
            "AVAILABLE",
          );

          const fallbackValue =
            result.record
              ?.total_emissions.value;

          expect(
            fallbackValue,
          ).not.toBeNull();

          expect(
            Number(
              fallbackValue,
            ),
          ).toBeGreaterThan(
            0,
          );
        }
      },
    );

    it(
      "preserves the India 3102 reference row",
      () => {
        const matches =
          records.filter(
            (record) =>
              record.origin_country_name ===
                "India"
              && record.normalized_trade_code ===
                "3102"
              && record.code_level ===
                "HS4",
          );

        expect(
          matches.length,
        ).toBe(1);

        expect(
          matches[0]
            ?.direct_emissions
            .status,
        ).toBe(
          "REFERENCE_REQUIRED",
        );

        expect(
          matches[0]
            ?.total_emissions
            .raw_source_value,
        ).toBe(
          "see below",
        );
      },
    );
  },
);